package com.saturn.demo.dao.bean;

import java.io.Serializable;
import java.util.Date;

public class DemoInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_info.id
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_info.name
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_info.create_time
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demo_info
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_info.id
     *
     * @return the value of demo_info.id
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_info.id
     *
     * @param id the value for demo_info.id
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_info.name
     *
     * @return the value of demo_info.name
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_info.name
     *
     * @param name the value for demo_info.name
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_info.create_time
     *
     * @return the value of demo_info.create_time
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_info.create_time
     *
     * @param createTime the value for demo_info.create_time
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_info
     *
     * @mbg.generated Thu Jun 27 12:43:04 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}